// SPDX-License-Identifier: 0BSD
// Writes docs/third-party.md: every Rust crate compiled into the wasm (see
// crates.ts) with its version, license and links, the parts of the Rust
// standard library linked in with them, the npm runtime dependencies and the
// build tools. The page is committed, so Read the Docs
// needs no Rust toolchain; CI regenerates it and fails when it is out of date.
// Usage: node scripts/gen-third-party.ts [output file]
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { STD_PARTS, rustVersion, shippedCrates } from './crates.ts';

const out = process.argv[2] ?? 'docs/third-party.md';

/** License file names, as gen-licenses.ts picks them. */
const LICENSE_FILE = /^(licen[cs]e|copying)/i;

/**
 * Links each SPDX identifier of a license expression to its SPDX page.
 * @param expr E.g. `(MIT OR Apache-2.0) AND Unicode-3.0`, or the old `MIT/Apache-2.0`.
 * @returns Markdown.
 */
function spdxLinks(expr: string): string {
  return expr.replace(/[A-Za-z0-9.+-]+/g, (id) =>
    ['AND', 'OR', 'WITH'].includes(id) ? id : `[${id}](https://spdx.org/licenses/${id.replace(/\+$/, '')}.html)`);
}

const rows = shippedCrates().map((c) => {
  const texts = readdirSync(dirname(c.manifest_path)).filter((f) => LICENSE_FILE.test(f)).sort();
  if (c.license_file !== null && !texts.includes(c.license_file)) texts.push(c.license_file);
  const license = [
    c.license === null ? 'see license text' : spdxLinks(c.license),
    // docs.rs serves every published crate's sources at the exact version.
    ...texts.map((f) => `[${f}](https://docs.rs/crate/${c.name}/${c.version}/source/${f})`),
  ].join('<br>');
  const source = c.repository === null ? '' : `[repository](${c.repository})`;
  return `| [${c.name}](https://crates.io/crates/${c.name}/${c.version}) | ${c.version} | ${license} | ${source} |`;
});
for (const p of STD_PARTS) {
  rows.push(`| Rust standard library: ${p.name} | ${rustVersion()} | ${spdxLinks(p.license)} | ` +
    `[repository](${p.repository}) |`);
}

const pkg = JSON.parse(readFileSync('package.json', 'utf8')) as {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
};
const npmDeps = Object.entries(pkg.dependencies ?? {});

const cargoToml = readFileSync('Cargo.toml', 'utf8');
const ciTools = readFileSync('scripts/ci-tools.sh', 'utf8');
/**
 * First capture of `re` in `text`.
 * @param text Source.
 * @param re Pattern with one group.
 * @param what For the error message.
 * @returns The match.
 */
function pick(text: string, re: RegExp, what: string): string {
  const m = re.exec(text)?.[1];
  if (m === undefined) throw new Error(`gen-third-party: ${what} not found`);
  return m;
}
const bindgen = pick(cargoToml, /^wasm-bindgen = "=([^"]+)"/m, 'wasm-bindgen version in Cargo.toml');
const binaryen = pick(ciTools, /^BINARYEN=(\d+)/m, 'BINARYEN in scripts/ci-tools.sh');
/**
 * Pinned version of a dev dependency.
 * @param name Package name.
 * @returns The version.
 */
function devVersion(name: string): string {
  const v = pkg.devDependencies?.[name];
  if (v === undefined) throw new Error(`gen-third-party: ${name} not in devDependencies`);
  return v;
}

const page = `<!-- SPDX-License-Identifier: 0BSD -->
<!-- Generated by scripts/gen-third-party.ts; do not edit. Run \`npm run docs:third-party\`. -->
# Third-party components

wav2flac itself is licensed 0BSD. The WebAssembly module also contains the
Rust crates below, and the parts of the Rust standard library that they use.
Their full license notices ship in the package as
\`THIRD_PARTY_LICENSES.txt\`, and each JS file of the package starts with a
\`/*! @license */\` comment that lists them.

The \`.wasm\` file itself carries no notices. If you host it yourself, for
example on a CDN, put \`THIRD_PARTY_LICENSES.txt\` next to it.

## Compiled into wav2flac.wasm

| Crate | Version | License | Source |
|---|---|---|---|
${rows.join('\n')}

## npm dependencies

${npmDeps.length === 0
    ? 'None. The package has no runtime `dependencies`.'
    : npmDeps.map(([name, range]) => `- [${name}](https://www.npmjs.com/package/${name}) ${range}`).join('\n')}

## Build tools (not shipped)

These build the package. They are not installed with it.

| Tool | Version | License |
|---|---|---|
| [Rust](https://www.rust-lang.org/) (rustc, cargo) | ${rustVersion()} | ${spdxLinks('MIT OR Apache-2.0')} |
| [wasm-bindgen-cli](https://github.com/wasm-bindgen/wasm-bindgen) | ${bindgen} | ${spdxLinks('MIT OR Apache-2.0')} |
| [binaryen](https://github.com/WebAssembly/binaryen) (wasm-opt) | ${binaryen} | ${spdxLinks('Apache-2.0')} |
| [esbuild](https://esbuild.github.io/) | ${devVersion('esbuild')} | ${spdxLinks('MIT')} |
| [TypeScript](https://www.typescriptlang.org/) | ${devVersion('typescript')} | ${spdxLinks('Apache-2.0')} |
`;
writeFileSync(out, page);
console.log(`  ${rows.length} components → ${out}`);
