# SPDX-License-Identifier: 0BSD
"""MkDocs hooks: point "Edit on GitHub" at the file to edit.

Some pages are not written in docs/: the home page is a copy of the README,
the third-party page is generated by a script, and the API reference is
generated from the TSDoc in ts/ and not checked in.
"""

# Pages whose source is elsewhere in the repository, relative to edit_uri.
SOURCES = {
    "index.md": "README.md",
    "third-party.md": "scripts/gen-third-party.ts",
}


def on_files(files, config):
    for file in files:
        if file.src_uri in SOURCES:
            file.edit_uri = SOURCES[file.src_uri]
        elif file.src_uri.startswith("reference/api/"):
            file.edit_uri = None
        else:
            file.edit_uri = "docs/" + file.src_uri
    return files
