// SPDX-License-Identifier: 0BSD
// Which branch `scripts/release.ts prepare` runs on: release/vX.Y.Z at
// origin/main, as .github/workflows/release.yml describes.
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

const SCRIPT = resolve('scripts/release.ts');
const REPO = 'https://github.com/julianhille/wav2flac';

// No GIT_* from the caller (a hook's GIT_DIR would point git elsewhere).
const env = {
  ...Object.fromEntries(Object.entries(process.env).filter(([k]) => !k.startsWith('GIT_'))),
  GIT_AUTHOR_NAME: 'test',
  GIT_AUTHOR_EMAIL: 'test@example.com',
  GIT_COMMITTER_NAME: 'test',
  GIT_COMMITTER_EMAIL: 'test@example.com',
  GIT_CONFIG_GLOBAL: '/dev/null',
  GIT_CONFIG_NOSYSTEM: '1',
};

let dir: string | undefined;
afterEach(() => {
  if (dir !== undefined) rmSync(dir, { recursive: true });
  dir = undefined;
});

/**
 * A clone at version 1.2.2 with an unreleased changelog entry, whose origin
 * has the same `main`.
 * @returns The clone's directory.
 */
function repo(): string {
  dir = mkdtempSync(join(tmpdir(), 'release-'));
  const work = join(dir, 'work');
  execFileSync('git', ['init', '--quiet', '--bare', join(dir, 'origin.git')], { env });
  mkdirSync(join(work, 'src'), { recursive: true });
  git(work, 'init', '--quiet', '--initial-branch', 'main');
  const files: Record<string, string> = {
    'src/lib.rs': '',
    'package.json': '{\n  "name": "wav2flac",\n  "version": "1.2.2"\n}\n',
    'package-lock.json':
      '{\n  "name": "wav2flac",\n  "version": "1.2.2",\n  "lockfileVersion": 3,\n' +
      '  "requires": true,\n  "packages": {\n    "": {\n      "name": "wav2flac",\n' +
      '      "version": "1.2.2"\n    }\n  }\n}\n',
    'Cargo.toml': '[package]\nname = "wav2flac"\nversion = "1.2.2"\nedition = "2021"\n',
    'Cargo.lock':
      '# This file is automatically @generated by Cargo.\n# It is not intended for manual ' +
      'editing.\nversion = 4\n\n[[package]]\nname = "wav2flac"\nversion = "1.2.2"\n',
    'CHANGELOG.md':
      '# Changelog\n\n## [Unreleased]\n\n### Fixed\n\n- A thing.\n\n' +
      '## [1.2.2] - 2026-01-01\n\n- Old.\n\n' +
      `[Unreleased]: ${REPO}/compare/v1.2.2...HEAD\n[1.2.2]: ${REPO}/releases/tag/v1.2.2\n`,
  };
  for (const [name, text] of Object.entries(files)) writeFileSync(join(work, name), text);
  git(work, 'add', '--all');
  git(work, 'commit', '--quiet', '--message', 'init');
  git(work, 'remote', 'add', 'origin', join(dir, 'origin.git'));
  git(work, 'push', '--quiet', 'origin', 'main');
  return work;
}

/**
 * Runs `git` in a directory.
 * @param cwd The directory.
 * @param args The arguments.
 * @returns Its output.
 */
function git(cwd: string, ...args: string[]): string {
  return execFileSync('git', args, { cwd, env, encoding: 'utf8' }).trim();
}

/**
 * Runs `release.ts prepare`.
 * @param cwd The repository.
 * @param v The version.
 * @returns The exit status and output.
 */
function prepare(cwd: string, v: string): { status: number | null; out: string; err: string } {
  const r = spawnSync(process.execPath, [SCRIPT, 'prepare', v], { cwd, env, encoding: 'utf8' });
  return { status: r.status, out: r.stdout, err: r.stderr };
}

describe('release.ts prepare', () => {
  it('commits the release on release/vX.Y.Z at origin/main', () => {
    const work = repo();
    git(work, 'switch', '--quiet', '--create', 'release/v1.2.3');
    const r = prepare(work, '1.2.3');
    expect(r.err).not.toMatch(/release:/);
    expect(r.status).toBe(0);
    expect(git(work, 'log', '-1', '--format=%s')).toBe('Release 1.2.3');
    expect(git(work, 'rev-parse', 'HEAD~1')).toBe(git(work, 'rev-parse', 'origin/main'));
    expect(r.out).toContain('git push origin release/v1.2.3 v1.2.3\n');
    expect(r.out).not.toMatch(/push origin main/);
  });

  it.each(['main', 'release/v1.2.4', 'release/1.2.3'])('refuses to run on %s', (branch) => {
    const work = repo();
    if (branch !== 'main') git(work, 'switch', '--quiet', '--create', branch);
    const head = git(work, 'rev-parse', 'HEAD');
    const r = prepare(work, '1.2.3');
    expect(r.status).toBe(1);
    expect(r.err).toBe(
      'release: releases are prepared on release/v1.2.3: ' +
        'git switch -c release/v1.2.3 origin/main\n',
    );
    expect(git(work, 'rev-parse', 'HEAD')).toBe(head);
  });

  it('refuses a release branch that is not at origin/main', () => {
    const work = repo();
    git(work, 'switch', '--quiet', '--create', 'release/v1.2.3');
    git(work, 'commit', '--quiet', '--allow-empty', '--message', 'extra');
    const head = git(work, 'rev-parse', 'HEAD');
    const r = prepare(work, '1.2.3');
    expect(r.status).toBe(1);
    expect(r.err).toBe('release: release/v1.2.3 is not at origin/main; start it from there\n');
    expect(git(work, 'rev-parse', 'HEAD')).toBe(head);
  });
});
